# Generated by Django 6.0.1 on 2026-03-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('queued', 'Queued')], default='queued', max_length=10)),
                ('endpoints_found', models.IntegerField(default=0)),
                ('vuln_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=500)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('finding_type', models.CharField(choices=[('BOLA', 'BOLA'), ('XSS', 'XSS'), ('SQLi', 'SQL Injection'), ('SSRF', 'SSRF'), ('RCE', 'RCE')], max_length=10)),
                ('is_confirmed_poc', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.scanreport')),
            ],
            options={
                'ordering': ['-cvss_score'],
            },
        ),
    ]
